### ISSUE TITLE
pbp-json-gen documentation

### ISSUE THREAD

**Issue by carueda** [mbari-org/pbp-doc#1]
Hi Danelle.

https://docs.mbari.org/pbp/pbp-json-gen/

**Comment by danellecline** [comment]
@carueda I'm working on updating the document in the branch jsongendoc. I hit an issue with the log output failing for the ICLISTEN output. Has something changed in the logger? The log output is created but it is zero bytes.

**Comment by danellecline** [comment]
@carueda here is the command that I tried

```
 pbp-json-gen --json-base-dir=json/iclisten \
                                                                           --output-dir=output \
                                                                           --uri=s3://pacific-sound-256khz \
                                                                           --start=20191023 \
                                                                           --end=20191024 \
                                                                           --prefix=MARS \
                                                                           --recorder=ICLISTEN
```

**Comment by danellecline** [comment]
The documentation has been updated.  It's a good foundation now to build with a support matrix, examples, etc., so I will close this.  

<img width="1029" alt="Screenshot 2024-07-11 at 5 58 02 PM" src="https://github.com/user-attachments/assets/c3b607dd-97bc-43e1-81b7-f5a80ece02bd">

<img width="1010" alt="Screenshot 2024-07-11 at 5 58 11 PM" src="https://github.com/user-attachments/assets/0528471a-cde4-4986-a8f8-4e42fc8befb1">

<img width="1060" alt="Screenshot 2024-07-11 at 5 59 00 PM" src="https://github.com/user-attachments/assets/9fa9b781-b205-4003-9f3e-6b16f4139e2d">
